services:
  srs_server:
    image: ossrs/srs:6
    container_name: rtmp_server
    networks:
      rtmp_net:
        ipv4_address: 172.20.0.2
    ports:
      - "1935:1935"
      - "1985:1985"
      - "8080:8080"
  video_publisher:
    image: ossrs/srs:encoder
    container_name: rtmp_publisher
    restart: on-failure
    networks:
      - rtmp_net
    entrypoint: ["/bin/sh", "-c", "sleep 10 && ffmpeg -stream_loop -1 -re -i doc/source.flv -c copy -f flv rtmp://172.20.0.2:1935/live/taller2"]
    depends_on:
      - srs_server
  vlc_client:
    image: lscr.io/linuxserver/vlc:latest
    container_name: rtmp_client
    networks:
      - rtmp_net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
    ports:
      - "3000:3000"
    depends_on:
      - srs_server
networks:
  rtmp_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
